### ISSUE TITLE
Not showing charts on iOS

### ISSUE THREAD

**Issue by guihendias** [ihadeed/ng2-chartjs2#1]
Hello, I liked this a lot and works fine, but the charts are not appearing when I switch to iphone on chrome device mode. Do you know how to fix it?

Thank you :D

**Comment by ihadeed** [comment]
I haven't experienced this issue so far. I will test it soon on an iOS simulator and try to reproduce your problem.

Could you also provide the code you used to create and display the charts?

Thanks!

**Comment by guihendias** [comment]
html tag:
 `<chart [options]="options"></chart>`
TS:

```
 labels: string[] = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"];

  data: Chart.Dataset[] = [
    {
      label: 'Vendas',
      data: [12, 19, 3, 5, 2, 3, 6],
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(255,255,255,0.2)'
      ],
      borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)',
        'rgba(0,0,0,0.2)'
      ],
      borderWidth: 1
    }
  ];
    options: Chart.Options = {
      type:'line',
      data: {
        labels: this.labels,
        datasets: this.data
      }
    };

```

Thanks.

**Comment by ihadeed** [comment]
Ok I will look into it soon.

FYI for your case it's better to use the new usage that is documented here. Make sure to update your npm package to v0.1.1 ( by running `npm i --save ng2-chartjs2@latest` ). The component can now take in your `data`, `labels` and `type` directly without having to create the options object yourself.

**Comment by guihendias** [comment]
Hey,

I just removed 'style.height = 0;' that was at Chart.bundle.js file, line 9832 and the charts are now shown correctly :smile: . This style attribute was causing the issue, so strange.

**Comment by guihendias** [comment]
Looks like the style bugs after page reload. If I open directly on iOS, it is shown correctly.

**Comment by ihadeed** [comment]
Then it's probably related to the responsive option (that is set to true by
default).

## 

*DISCLAIMER: *This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.

**Comment by ihadeed** [comment]
Hey @guihendias are you working on a regular Angular 2 app or is it an Ionic 2 app?

**Comment by guihendias** [comment]
@ihadeed, an Ionic 2 App.

**Comment by smukov** [comment]
Setting the `responsive : false` fixed it for me.

```
options: Chart.Options = {
    type:'line',
    data: {
      labels: this.labels,
      datasets: this.data
    },
    options: {
      responsive : false
    }
  };
```

**Comment by ihadeed** [comment]
Just tested this with the latest version of Ionic (rc0) and ng2-chartjs2 (1.1.0) and it's working fine. Please let me know if you guys are still having this issue.
