### ISSUE TITLE
typo in call to this.chart.destroy

### ISSUE THREAD

**Issue by BenMens** [ihadeed/ng2-chartjs2#11]
There is is typo in the call to this.chart.destroy. In the code you use this.chart.destory.
Note that the o and r are switched.

This results in an exception: TypeError: this.chart.destory is not a function(…)

BTW: thanks for putting this module together

**Comment by ihadeed** [comment]
Should be fixed now, please update to `ng2-chartjs2@1.1.2`

**Comment by BenMens** [comment]
Great. Thanks.
