### ISSUE TITLE
Integrate Chart.Zoom.js

### ISSUE THREAD

**Issue by felixmagno** [ihadeed/ng2-chartjs2#12]
It is posible use the zoom y panning in ionic2? https://github.com/chartjs/Chart.Zoom.js

Thanks!

**Comment by ihadeed** [comment]
Not at the moment, but I'll look into it soon.

Seems like I just need to add the needed options to the interface, and you
will need to include a second JS file in your build.

I'm not sure about Ionic 2 compatibility, but their Github README does say
that you can zoom and pan using touch events. So I assume that it works
fine.

I will look into this soon.

**Comment by felixmagno** [comment]
It would be great. We'll wait enthusiastically. 

Thank you very much. Regards!

**Comment by ihadeed** [comment]
@felixmagno done! 

Now you can add the zoom/pan options just as the Chart.Zoom.js repo demonstrates.

Please update your `ng2-chartjs2` to `1.2.0`.

**Comment by felixmagno** [comment]
@ihadeed Thank you very much! 
It's work in ios app and browser, but in Android I have problem with touch gesture. I´ll continue investigating.

Regards!

**Comment by ihadeed** [comment]
@felixmagno thanks for the feedback. Keep me posted.
