### ISSUE TITLE
type stand-alone parameter ignored 

### ISSUE THREAD

**Issue by Dill1** [ihadeed/ng2-chartjs2#2]
According to the documentation this should be allowed, which I think is a very good design:
`template: '<chart [labels]="labels" [data]="data" type="line"></chart>',
`
However, type is ignored and always set to "bar". See http://stackoverflow.com/questions/38617697/ng2-chartjs2-ignores-type-and-always-shows-a-bar-chart.

**Comment by ihadeed** [comment]
Sorry about that, I just fixed it here https://github.com/zyramedia/ng2-chartjs2/commit/460619f26d4f5cce159e9a47ce3d2d732a87f491

I also updated the npm package.
