### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by fishgrind** [ihadeed/ng2-chartjs2#7]
The Angular team suggest that library vendors should also ship .metadata.json files. These files are produced automatically by ngc. Without it we get compile errors.

Your might find below comments useful:

Complete conversation (angular/angular#11262)

**Comment by ihadeed** [comment]
Thank you I will look into this soon.

**Comment by fishgrind** [comment]
Thanks for updating!

I am going to test it soon!

**Comment by ihadeed** [comment]
Update to `1.1.0`. Please refer to readme for updated instructions. The package now exports `ChartModule` that you can import in your app, instead of importing ChartComponent.
