### ISSUE TITLE
ChartComponent not exported in RC0?

### ISSUE THREAD

**Issue by cedWetzel** [ihadeed/ng2-chartjs2#8]
Hey, this has worked out perfectly in pre RC0 era but since I have updated to RC0 and the new Angular NgModule declarations I always get the following error:

> graphTest/node_modules/ng2-chartjs2/index.js does not export ChartComponent

Do you have any clue about this?

**Comment by ihadeed** [comment]
Please try the latest version `1.0.0`

**Comment by ihadeed** [comment]
Please try the latest version `1.1.0`. The library now exports `ChartModule` that you can import in your main app module. This should resolve your issue.
